-- ─────────────────────────────────────────────────────────────────────────────
-- Parity slice 4 — the Profile tab (prototype S_profiletab, the OWN render,
-- 10565-11400). The page prints five things about a person that no column
-- held: what they have to say for themselves (About, ≤ 220 chars — the sheet's
-- own limit, 11390), their age ("24, New Delhi" — the number alone, 10664),
-- the links where else to find them (a rail of platform chips, 10760), the
-- styles they dance (dosMyStyles 1719 — "saved, not held in this page's head"),
-- and the account number beside the role ("000482", 10641).
--
-- Every one is the person's OWN to say and nobody else's to set, so there is
-- ONE door — update_my_profile — scoped to auth.uid() inside the function, and
-- no new policy: profiles already lets a signed-in user read live rows and
-- update their own (Step 1). The door validates what a form cannot be trusted
-- to: a link is an http(s) URL naming a known platform or a short label, a
-- style is a short word, an age is a plausible one.
--
-- Deliberately NOT here: a `verified` flag (the prototype draws the tick on
-- everybody — a verification nobody performs is a badge that means nothing),
-- and a rank ladder (Step 25's place is printed with its population instead).
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.profiles
  add column about text check (about is null or char_length(about) <= 220),
  add column age smallint check (age is null or (age >= 13 and age <= 99)),
  add column socials jsonb not null default '[]'::jsonb
    check (jsonb_typeof(socials) = 'array' and jsonb_array_length(socials) <= 12),
  add column styles text[] not null default '{}'::text[]
    check (cardinality(styles) <= 12),
  add column member_no bigint generated by default as identity;

create unique index profiles_member_no_key on public.profiles (member_no);

comment on column public.profiles.about is
  'The person''s own sentence (S_profiletab About, ≤ 220 chars). Null prints nothing — never a default bio in somebody else''s words.';
comment on column public.profiles.age is
  'The age the person states (13–99). Printed as the number alone: "24, New Delhi".';
comment on column public.profiles.socials is
  'A list of {platform, url} in the order the person arranged them (S_profiletab 10760). Platform is one of the known names or a short custom label.';
comment on column public.profiles.styles is
  'The styles the person dances, in their order (dosMyStyles 1719). A person''s claim — a business''s styles are read off its classes instead.';
comment on column public.profiles.member_no is
  'The account number printed beside the role (000482). Assigned once, never reused.';

-- ── the one door ──────────────────────────────────────────────────────────────
create or replace function public.update_my_profile(
  p_full_name text,
  p_city text,
  p_age smallint,
  p_about text,
  p_socials jsonb,
  p_styles text[]
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_item jsonb;
  v_platform text;
  v_url text;
  v_style text;
  v_seen text[] := '{}';
  v_styles text[] := '{}';
begin
  if v_user is null then
    raise exception 'not authenticated';
  end if;
  if p_full_name is null or char_length(btrim(p_full_name)) < 1 or char_length(p_full_name) > 120 then
    raise exception 'a name is 1 to 120 characters';
  end if;
  if p_city is not null and char_length(p_city) > 120 then
    raise exception 'that city name is too long';
  end if;
  if p_age is not null and (p_age < 13 or p_age > 99) then
    raise exception 'an age is between 13 and 99';
  end if;
  if p_about is not null and char_length(p_about) > 220 then
    raise exception 'about is at most 220 characters';
  end if;

  -- links: an array of {platform, url}; a url is http(s) and a platform a short word
  if p_socials is null or jsonb_typeof(p_socials) <> 'array' then
    raise exception 'links must be a list';
  end if;
  if jsonb_array_length(p_socials) > 12 then
    raise exception 'at most 12 links';
  end if;
  for v_item in select * from jsonb_array_elements(p_socials) loop
    if jsonb_typeof(v_item) <> 'object' then
      raise exception 'a link is a platform and a url';
    end if;
    v_platform := btrim(v_item ->> 'platform');
    v_url := btrim(v_item ->> 'url');
    if v_platform is null or char_length(v_platform) < 1 or char_length(v_platform) > 40 then
      raise exception 'a link needs a platform or a label (up to 40 characters)';
    end if;
    if v_url is null or char_length(v_url) > 300 or v_url !~* '^https?://[^[:space:]]+$' then
      raise exception 'a link is a web address starting with http:// or https://';
    end if;
    if v_platform = any (v_seen) then
      raise exception 'one link per platform';
    end if;
    v_seen := array_append(v_seen, v_platform);
  end loop;

  -- styles: short words, de-duplicated, in the order given
  if p_styles is null then
    raise exception 'styles must be a list';
  end if;
  foreach v_style in array p_styles loop
    v_style := btrim(v_style);
    if v_style is null or char_length(v_style) < 1 or char_length(v_style) > 40 then
      raise exception 'a style is 1 to 40 characters';
    end if;
    if not (v_style = any (v_styles)) then
      v_styles := array_append(v_styles, v_style);
    end if;
  end loop;
  if cardinality(v_styles) > 12 then
    raise exception 'at most 12 styles';
  end if;

  update public.profiles
     set full_name = btrim(p_full_name),
         city = nullif(btrim(p_city), ''),
         age = p_age,
         about = nullif(btrim(p_about), ''),
         socials = p_socials,
         styles = v_styles,
         updated_by = v_user
   where id = v_user and deleted_at is null;
  if not found then
    raise exception 'finish onboarding first';
  end if;
end;
$$;

revoke execute on function public.update_my_profile(text, text, smallint, text, jsonb, text[]) from public, anon;
grant execute on function public.update_my_profile(text, text, smallint, text, jsonb, text[]) to authenticated;
